### PR TITLE
Imported web app

### PR DESCRIPTION
**Pull request by spramij**
Copied over what I had done on a private repo.
Consult `readme.md` for explanations and instructions.
- Flask based, powered by Bootstrap, JS, InfluxDB

### CODE REVIEW

**Comment by Newfloridadad** [comment]
Add one more dir layer here because we will have multiple OnLand projects. so OnLand/ControlLaptop/ files here, or similar OnLand/WebAppControlConsole/

**Comment by spramij** [comment]
@stuckatmarine 
Fixed dir layer, added examples and documentation for it.

**Comment by mmb186** [comment]
- Add installation guide for influx DB and related dependencies. (inside doc/ maybe?)
- We should be using virtualenv and pyenv for this project, so add a guide to set that up.
- This project structure is fine for now, but divide the app.py into appropriate files so it is more readable. (IE: utilities.py, routes.py ect) 
- Add __pycache__/ and *.pyc to the .gitignore

Let me know if you need help with any of the following!

**Comment by spramij** [comment]
@mmb186 
Added instructions for Influx, venv, and pip requirements in `readme.md`. Will have to double check the `.gitignore`, but it seemed to be doing what it's supposed to. As for the project structure, I'll take a stab at it later this weekend.

Edit: seemed to have broken the `.gitignore`, some `OnPod` C stuff got through.

Edit 2: included instructions are for Linux systems, if enough people are using Windows I'll research how to set up Influx and the rest on it. 

Edit 3: I done goofed up. Will fix it later this weekend

**Review by lwaghorn — APPROVED** [review]

**Pull request merged**
